### ISSUE TITLE
Function name must be a string

### ISSUE THREAD

**Issue by yordanoff** [jbeyerstedt/kirby-plugin-kirbytextRaw#12]
The `ktr()` function doesn't work on Kirby 3.0.3. Here's what I get: https://cl.ly/5cc2af059803

**Comment by yordanoff** [comment]
Nevermind, I've downloaded from the wrong branch. Sorry about that, everything works great. 

And the plugin is super awesome, by the way. Thank you for your work!

**Comment by yordanoff** [comment]
Nevermind, I've downloaded it from the wrong branch. Sorry about that, everything works great.

And the plugin is super awesome, by the way. Thank you for your work!

**Comment by jbeyerstedt** [comment]
I don't know, if it would have been a better solution to create a new repository for the Kirby 3 version. Maybe I should change the default branch here at github now.

Currently I don't have much time to take care of my kirby plugins and I hadn't had a closer look at kirby 3. As far as I've read the documentation, this plugin might not be needed any more, because the `kirbytags()` method does what I wanted to achieve in the first place. It should render all kirbytags, but not evaluate the markdown.
